# netlify.toml (na raiz do repositório)

[build]
  # Monorepo: o app está dentro de "frontend"
  base = "frontend"
  # O build do Vite/React
  command = "npm ci && npm run build"
  # Saída do Vite relativa ao base
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# SPA fallback para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
